### ISSUE TITLE
no build instructions. unreal to compile

### ISSUE THREAD

**Issue by luntik2012** [liftoff-sr/CIPster#1]
I think this is invalid snippet: "<path-to-CIPster&gt/examples/WINDOWS"

I've done this

---

D:\src\CIPster\build>cmake -DCMAKE_TOOLCHAIN_FILE=D:\src\CIPster\source\buildsup
port\Toolchain\toolchain-mingw64.cmake -DCMAKE_BUILD_TYPE=Debug D:\src\CIPster\e
xamples\WINDOWS
-- Building for: Visual Studio 12 2013
-- The C compiler identification is MSVC 18.0.21005.1
-- The CXX compiler identification is MSVC 18.0.21005.1
-- Check for working C compiler using: Visual Studio 12 2013
-- Check for working C compiler using: Visual Studio 12 2013 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler using: Visual Studio 12 2013
-- Check for working CXX compiler using: Visual Studio 12 2013 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: D:/src/CIPster/build

---

I don't know, why is it building for msvc2013
But ok, I open "CIPster on Linux.sln" in msvc2013:

---

1>------ Build started: Project: ZERO_CHECK, Configuration: Debug Win32 ------
1>  Checking Build System
1>  CMake does not need to re-run because D:/src/CIPster/build/CMakeFiles/generate.stamp is up-to-date.
2>------ Build started: Project: eip, Configuration: Debug Win32 ------
2>  Building Custom Rule D:/src/CIPster/examples/WINDOWS/CMakeLists.txt
2>  CMake does not need to re-run because D:\src\CIPster\build\CMakeFiles\generate.stamp is up-to-date.
2>  Creating directories for 'eip'
2>  No download step for 'eip'
2>  No update step for 'eip'
2>  No patch step for 'eip'
2>  Performing configure step for 'eip'
2>  -- Building for: Visual Studio 12 2013
2>  -- The C compiler identification is MSVC 18.0.21005.1
2>  -- The CXX compiler identification is MSVC 18.0.21005.1
2>  -- Check for working C compiler using: Visual Studio 12 2013
2>  -- Check for working C compiler using: Visual Studio 12 2013 -- works
2>  -- Detecting C compiler ABI info
2>  -- Detecting C compiler ABI info - done
2>  -- Check for working CXX compiler using: Visual Studio 12 2013
2>  -- Check for working CXX compiler using: Visual Studio 12 2013 -- works
2>  -- Detecting CXX compiler ABI info
2>  -- Detecting CXX compiler ABI info - done
2>  -- Detecting CXX compile features
2>  -- Detecting CXX compile features - done
2>  -- Looking for srand
2>  -- Looking for srand - found
2>  -- Looking for rand
2>  -- Looking for rand - found
2>  OBJECTS_SRC:
2>  CMAKE_INSTALL_PREFIX:D:/src/CIPster/build/build-CIPster
2>  -- Configuring done
2>  -- Generating done
2>  -- Build files have been written to: D:/src/CIPster/build/build-CIPster/src/eip-build
2>  Performing build step for 'eip'
2>  make: **\* No targets specified and no makefile found.  Stop.
2>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(170,5): error MSB6006: "cmd.exe" exited with code 2.
3>------ Build started: Project: sample, Configuration: Debug Win32 ------
3>  Building Custom Rule D:/src/CIPster/examples/WINDOWS/CMakeLists.txt
3>  CMake does not need to re-run because D:\src\CIPster\build\CMakeFiles\generate.stamp is up-to-date.
3>cl : Command line warning D9002: ignoring unknown option '-std=c++0x'
3>  main.cc
3>  networkhandler.cc
3>D:\src\CIPster\examples\WINDOWS\networkhandler.cc(181): warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
3>          D:\soft\msvs2013_x86\VC\include\string.h(168) : see declaration of 'strerror'
3>D:\src\CIPster\examples\WINDOWS\networkhandler.cc(210): warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
3>          D:\soft\msvs2013_x86\VC\include\string.h(168) : see declaration of 'strerror'
3>D:\src\CIPster\examples\WINDOWS\networkhandler.cc(224): warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
3>          D:\soft\msvs2013_x86\VC\include\string.h(168) : see declaration of 'strerror'
3>D:\src\CIPster\examples\WINDOWS\networkhandler.cc(261): warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
3>          D:\soft\msvs2013_x86\VC\include\string.h(168) : see declaration of 'strerror'
3>D:\src\CIPster\examples\WINDOWS\networkhandler.cc(295): warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
3>          D:\soft\msvs2013_x86\VC\include\string.h(168) : see declaration of 'strerror'
3>D:\src\CIPster\examples\WINDOWS\networkhandler.cc(306): warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
3>          D:\soft\msvs2013_x86\VC\include\string.h(168) : see declaration of 'strerror'
3>D:\src\CIPster\examples\WINDOWS\networkhandler.cc(369): warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
3>          D:\soft\msvs2013_x86\VC\include\string.h(168) : see declaration of 'strerror'
3>D:\src\CIPster\examples\WINDOWS\networkhandler.cc(384): warning C4805: '==' : unsafe mix of type 'bool' and type 'EipBool8' in operation
3>D:\src\CIPster\examples\WINDOWS\networkhandler.cc(459): warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
3>          D:\soft\msvs2013_x86\VC\include\string.h(168) : see declaration of 'strerror'
3>D:\src\CIPster\examples\WINDOWS\networkhandler.cc(493): warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
3>          D:\soft\msvs2013_x86\VC\include\string.h(168) : see declaration of 'strerror'
3>D:\src\CIPster\examples\WINDOWS\networkhandler.cc(499): warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
3>          D:\soft\msvs2013_x86\VC\include\string.h(168) : see declaration of 'strerror'
3>D:\src\CIPster\examples\WINDOWS\networkhandler.cc(525): warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
3>          D:\soft\msvs2013_x86\VC\include\string.h(168) : see declaration of 'strerror'
3>D:\src\CIPster\examples\WINDOWS\networkhandler.cc(532): warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
3>          D:\soft\msvs2013_x86\VC\include\string.h(168) : see declaration of 'strerror'
3>D:\src\CIPster\examples\WINDOWS\networkhandler.cc(552): warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
3>          D:\soft\msvs2013_x86\VC\include\string.h(168) : see declaration of 'strerror'
3>D:\src\CIPster\examples\WINDOWS\networkhandler.cc(558): warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
3>          D:\soft\msvs2013_x86\VC\include\string.h(168) : see declaration of 'strerror'
3>D:\src\CIPster\examples\WINDOWS\networkhandler.cc(635): warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
3>          D:\soft\msvs2013_x86\VC\include\string.h(168) : see declaration of 'strerror'
3>D:\src\CIPster\examples\WINDOWS\networkhandler.cc(658): warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
3>          D:\soft\msvs2013_x86\VC\include\string.h(168) : see declaration of 'strerror'
3>D:\src\CIPster\examples\WINDOWS\networkhandler.cc(677): warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
3>          D:\soft\msvs2013_x86\VC\include\string.h(168) : see declaration of 'strerror'
3>D:\src\CIPster\examples\WINDOWS\networkhandler.cc(693): warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
3>          D:\soft\msvs2013_x86\VC\include\string.h(168) : see declaration of 'strerror'
3>D:\src\CIPster\examples\WINDOWS\networkhandler.cc(748): warning C4805: '==' : unsafe mix of type 'bool' and type 'EipBool8' in operation
3>D:\src\CIPster\examples\WINDOWS\networkhandler.cc(757): warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
3>          D:\soft\msvs2013_x86\VC\include\string.h(168) : see declaration of 'strerror'
3>D:\src\CIPster\examples\WINDOWS\networkhandler.cc(782): warning C4805: '==' : unsafe mix of type 'bool' and type 'EipBool8' in operation
3>D:\src\CIPster\examples\WINDOWS\networkhandler.cc(800): warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
3>          D:\soft\msvs2013_x86\VC\include\string.h(168) : see declaration of 'strerror'
3>D:\src\CIPster\examples\WINDOWS\networkhandler.cc(845): warning C4805: '==' : unsafe mix of type 'bool' and type 'EipBool8' in operation
3>D:\src\CIPster\examples\WINDOWS\networkhandler.cc(863): warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
3>          D:\soft\msvs2013_x86\VC\include\string.h(168) : see declaration of 'strerror'
3>D:\src\CIPster\examples\WINDOWS\networkhandler.cc(908): warning C4805: '==' : unsafe mix of type 'bool' and type 'EipBool8' in operation
3>D:\src\CIPster\examples\WINDOWS\networkhandler.cc(926): warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
3>          D:\soft\msvs2013_x86\VC\include\string.h(168) : see declaration of 'strerror'
3>D:\src\CIPster\examples\WINDOWS\networkhandler.cc(984): warning C4805: '==' : unsafe mix of type 'bool' and type 'EipBool8' in operation
3>D:\src\CIPster\examples\WINDOWS\networkhandler.cc(1004): warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
3>          D:\soft\msvs2013_x86\VC\include\string.h(168) : see declaration of 'strerror'
3>  sampleapplication.cc
3>  Generating Code...
3>LINK : warning LNK4012: invalid value 'X86;-static', must be 'ARM, EBC, X64, or X86'; option ignored
3>LINK : fatal error LNK1181: cannot open input file 'build-CIPster\libeip.a'
4>------ Skipped Build: Project: ALL_BUILD, Configuration: Debug Win32 ------
4>Project not selected to build for this solution configuration 
========== Build: 1 succeeded, 2 failed, 0 up-to-date, 1 skipped ==========

**Comment by liftoff-sr** [comment]
Nikita,

Sorry, I do not have a windows machine here and will not be able to help anyone building
on or for Windows on my nickel.  The build instructions in README.me are currently for
building on linux; for windows.  Not building on windows.

But generally:
If you have mingw installed, then you may not need the toolchain file to build on windows.
 You just have to have the tools on your PATH, and then tell cmake on the initial
invocation that you want to build a GCC/MINGW type makefile/project.

If there is enough interest, we can create a mailing list and get contributions from a
community effort to offer better support for build _ON_ Windows.  But it won't be me
embellishing that support.

**Comment by luntik2012** [comment]
I can try fr msvc2015 tomorrow, but I hate it. I really don't want to make it run on my win pc, but it's my job:) I'll try on mingw also and post results here
