### ISSUE TITLE
How to send and receive data through this program?

### ISSUE THREAD

**Issue by SmartPointer1** [liftoff-sr/CIPster#11]
Hi ,
How to send and receive data through this program, it seems that there is no data sent and received in the example.

**Comment by liftoff-sr** [comment]
The sample programs play the role of an adapter.  Adapter = server = target.  It will speak when spoken to by a scanner.  Scanner = client = originator.

**Comment by jadamroth** [comment]
I know this is an old issue, but we've been working on an open source EtherNet/IP scanning library - github.com/nimbuscontrols/EIPScanner

Feel free to use for testing with this repo!
