### ISSUE TITLE
How to check the sample ? can we have any slave ?

### ISSUE THREAD

**Issue by shangarnithi** [liftoff-sr/CIPster#12]
Hi,

How to check the sample code? can we have any slave implementation?

**Comment by liftoff-sr** [comment]
> How to check the sample code? 

with a compiler and a computer?

can we have any slave implementation?

mostly.

**Comment by shangarnithi** [comment]
Yeah Between two computers . 

Can you please share the path of the master and slave implementation and procedure to test it ??

Apologies for the late reply .

**Comment by liftoff-sr** [comment]
This is not a mailing list.  This is an issue manager.  Your issue is that you don't know
squat about Ethernet/IP, which is not really an issue with the software itself, so is IMO
not an issue to be discussed HERE.  That is what the freelist mailing list is for.

**Comment by liftoff-sr** [comment]
On 2/22/19 1:09 AM, shangarnithi wrote:
> Yeah Between two computers .
> 
> Can you please share the path of the master and slave implementation and procedure to test
> it ??
> 
> Apologies for the late reply .

You might try asking for help on the project's mailing list from "anyone" for hints.  I
cannot give such time away for free myself.
