### ISSUE TITLE
EtherNET/IP resources

### ISSUE THREAD

**Issue by JoeyR** [liftoff-sr/CIPster#17]
Hello,

I am looking at integrating a couple of devices that support EtherNET/IP and I am wondering if you could point me in the right direction.

1. Do you have any go-to whitepapers for the EtherNET/IP protocol?
2. If I have the device's EDS file, what is needed from that to communicate with a device? (or is it parsed when you open the connection?)

Thank you for your time,
JoeyR

**Comment by liftoff-sr** [comment]
There is a mailing list for general discussions.  This issue tracker is for bugs or enhancement requests.

**Comment by JoeyR** [comment]
It was worth a shot, thank you.
