### ISSUE TITLE
the sample source code for the CIP master station?

### ISSUE THREAD

**Issue by bzyang** [liftoff-sr/CIPster#2]
I am using the CIP protocol for data acquisition equipment, the need for a CIP master source. Can you provide the sample source code for the CIP master station?
Thanks

**Comment by liftoff-sr** [comment]
On 08/29/2016 04:20 AM, bzyang wrote:
> I am using the CIP protocol for data acquisition equipment, the need for a CIP master
> source. Can you provide the sample source code for the CIP master station?
> Thanks


Hi bzyang,

I have no source of a CIP master station at this time.  I would like to have it, and will
likely develop it eventually as time permits, unless someone else contributes it first.

Thanks for asking.
