### ISSUE TITLE
Is it possible to build project with mingw under Windows?

### ISSUE THREAD

**Issue by owbeg** [liftoff-sr/CIPster#20]
I tried to build CIPster sample application under Windows 7 (Windows 10) 64 bit.
I installed mingw64 (release 8.1)0 and cmake (version 3.2) but cmake also prepare project to build with Visual Studio even I tried to define CMAKE_TOOLCHAIN_FILE variable (with -DCMAKE_TOOLCHAIN_FILE=<path-to-mingw-toolchain-file>) in cmake call.

I aslo tried to compile with Visual Studio but compilation finished with error - in the file byte_bufs.h is used datatype "ssize_t" whicj is not defined under Windows

**Comment by liftoff-sr** [comment]
https://stackoverflow.com/questions/51509173/how-can-i-make-cmake-use-mingw-w64-gcc-g

One of the answers to the question asked in this thread might get you further along.
There might be additional hurdles after you clear this one however.
I don't have Windows installed so I've not seen what lies ahead of you.
⁣

**Comment by owbeg** [comment]
Thanks, stackoverflow post you mentioned guide me in right direction.
It is required steps to compile CIPstre under windows with MinGw:
1. Install MinGw-64 (I installed release 7.3)
2. (!!!) copy file mingw32-make.exe under <MinGw insatllation path>\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin folder to file with name "make.exe", otherwise building project will fail with error (somewhere in the project files name of "make" program is hardcoded, I tried to add variable CMAKE_MAKE_PROGRAM to the <CIPster source folder>\source\buildsupport\Toolchain\toolchain-mingw64.cmake file but this didn't help):
=============================================================
[ 54%] Performing build step for 'eip'
"make" не является внутренней или внешней командой, исполняемой программой или пакетным файлом.
mingw32-make[2]: *** [CMakeFiles\eip.dir\build.make:85: build-CIPster/src/eip-stamp/eip-build] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:84: CMakeFiles/eip.dir/all] Error 2
mingw32-make: *** [Makefile:90: all] Error 2
=============================================================

3. Run MinGw terminal (from the "MinGW-W64 Project" program ftoup) to be sure MinGw environment configured correctly 
4. In MinGw terminal define variable CMAKE_GENERATOR:
set CMAKE_GENERATOR=MinGW Makefiles

5. Create build directory :
mkdir CIPstre_build
cd CIPstre_build

6. Run cmake:
cmake -DCMAKE_TOOLCHAIN_FILE=<CIPster sources folder>\source\buildsupport\Toolchain\toolchain-mingw64.cmake -DCMAKE_BUILD_TYPE=Debug ..\CIPster\examples\WINDOWS

7. Run make:
mingw32-make
