### ISSUE TITLE
Stack re-entrance issues.

### ISSUE THREAD

**Issue by acidtonic** [liftoff-sr/CIPster#25]
I am having issues with some kind of global state or re-entrance issue if I completely bring the stack down and simply bring it back up again.

The behavior is that the stack comes up and properly binds/listens. It accepts the connection and starts communication, but oddly none of the new ByteBufs ever see updated values from the PLC.

I am not stopping via a signal handler but rather the g_endStack variable, cleaning up by calling NetworkHandlerFinish() and finally ShutdownCipStack();

I then bring it back up again later by repeating the initialization procedure, I have tried using a different connection number or reusing it as a test and both ways result in the same behavior described above. I have also tried registering assemblies at a different CIP address upon restarting it and still the new address assemblies do not show updated values as the PLC communicates.

Just curious if I am missing anything or if this is something the library was coded to do? I simply desire to stop the CIP server, register different assemblies at different addresses, and bring it back up again.

**Comment by acidtonic** [comment]
Still fighting this, I'm about to just start over with a clean slate.

Unfortunately my fix is basically going down the rabbit hole of rewriting everything to not be global static. Callbacks switched to functors over globals, etc. fd_set is not happy being static after re-entrance and as I keep moving things out I'm starting to see lots of unchecked error paths without tracing or logging. Half the paths blindly return OK when lots of seriously things are wrong like bad sequence numbers.

Upon bringing things back up without the process exiting, select() never returns anything other than 0 for the read set and thus the udp handler never gets drained. I mucked around with making fd_set non static and it seems oddly now I hit blocking behavior in places where it's completely unexpected.

I can validate with wireshark that packets continue to flow, new cip sessions are registered, sockets rebinded with new fds, but then select() stops working. I can see writes going out but no reads.

I am not sure how much more effort I can put into this without simply moving it to C++20 and cleaning up everything upon which I guess I'll just make it a brand new library with a new name. The intentional lack of tag support is also getting irritating. I'm about done kicking a dead horse.

**Comment by liftoff-sr** [comment]
Questions:
1) Which operating systems are you targeting with your scripting tool?
2) What language is the scripting tool?
3) What tool are your using to create the bindings to that scripting language?
4) Did you make the list I suggested of activities during stack initialization?  (If so please send it to me.)
