### ISSUE TITLE
show issue when compile it on ubuntu for windows

### ISSUE THREAD

**Issue by jiansiting** [liftoff-sr/CIPster#30]
[  4%] Building CXX object src/CMakeFiles/eip.dir/cip/ciptcpipinterface.cc.obj
/home/***/CIPster-master/source/src/cip/ciptcpipinterface.cc:18:10: fatal error: arpa/inet.h: No such file or directory
   18 | #include <arpa/inet.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[5]: *** [src/CMakeFiles/eip.dir/build.make:260: src/CMakeFiles/eip.dir/cip/ciptcpipinterface.cc.obj] Error 1
make[4]: *** [CMakeFiles/Makefile2:122: src/CMakeFiles/eip.dir/all] Error 2
make[3]: *** [Makefile:130: all] Error 2
make[2]: *** [CMakeFiles/eip.dir/build.make:112: build-CIPster/src/eip-stamp/eip-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/eip.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

---------------------------------------------------------------------------------------------------------------------
How to solve it?

**Comment by liftoff-sr** [comment]
Fixed:
https://github.com/liftoff-sr/CIPster/commit/164c94a16cee23e9721396bab918ffe7b310d3c4
