### ISSUE TITLE
Communication with a device that communicates with Ethernet/ip

### ISSUE THREAD

**Issue by pucciland95** [liftoff-sr/CIPster#39]
Hi,

I am very new to this topic, so I apologise in advance if this question is confusing.

I have a Schunk Gripper that communicates through Ethernet/ip with external devices. I want to be able to receive and send data to this device using this library. Honestly, I am very confused how it works and from where to start.
I did not even understand whether this library is what I am looking for or not. 
Can someone of the authors enlighten me or provide me with some documentation where I can understand how to proceed? 

Cheers,

Niccolo

**Comment by liftoff-sr** [comment]
On 3/20/24 12:48, Niccolo wrote:
> Schunk Gripper

Niccolo,

Please send the usersmanual or similar where it goes into detail on the support of your device for Ethernet/IP.

It is likely that such support is more along the lines of an adapter (slave) than a scanner (master).

But there's no need to guess if you can provide clear documentation.

Dick

**Comment by pucciland95** [comment]
Hi,

thank you for the fast response.
In this pdf [here](https://github.com/liftoff-sr/CIPster/files/14691805/EGK-40-Doc.pdf) at page 12/120 there is an explanation about how the data exchange works. 
From what you are saying I suppose that my personal pc should be the adapter and the external device the scanner.
May I ask you if this repo provides the implementation for the scanner (master) or the adapter (slave)?

Niccolo
