### ISSUE TITLE
Do this stack support Class 1 Cyclic Triggered I/O connection?

### ISSUE THREAD

**Issue by xixi647** [liftoff-sr/CIPster#4]
Hi, 
Do this stack support Class 1 Cyclic Triggered I/O connection?

I read the code, and it seem not. 
could you help clear this confusions?

**Comment by liftoff-sr** [comment]
On 10/17/2017 02:20 AM, xixi647 wrote:
> Hi,
> Do this stack support Class 1 Cyclic Triggered I/O connection?
> 
> I read the code, and it seem not.
> could you help clear this confusions?


Cyclic definitely yes, as an adapter (=server) not a scanner (=client).

CIP Volume 1_3.20 section 3-4.4.3
